project_name: proksi
builds:
  - main: build.go
    goarch:
      - amd64
    binary: proksi
    hooks:
      post: sh build-cross-release.sh
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
archives:
  - id: tar.gz
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  - id: binary
    format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
release:
  disable: false
