project_name: proksi
builds:
  -
    main: build.go
    goarch:
      - amd64
    binary: proksi
    hooks:
      post: sh build-cross-release.sh
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
release:
  disable: false
