project_name: proksi
builds:
  - main: build.go
    goarch:
      - amd64
    binary: proksi
    hooks:
      post: sh build-cross-release.sh
archives:
  - id: tar.gz
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}'
  - id: binary
    format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}'
checksum:
  name_template: 'checksums.txt'
release:
  disable: false
