[package]
name = "proksi"
description = "A batteries-included reverse proxy with automatic HTTPS using Cloudflare Pingora and Let's Encrypt."
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
license-file = "LICENSE"
keywords = ["proxy", "https", "reverse-proxy", "load-balancer", "pingora"]
categories = ["web-programming::http-server", "network-programming"]
exclude = ["examples/", "dist/", "target/", "tests/"]
authors = ["The Proksi Contributors <toaster.chicory-0b@icloud.com>"]
rust-version = "1.78.0"
readme = "README.md"
homepage = "https://github.com/luizfonseca/proksi"
repository = "https://github.com/luizfonseca/proksi"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = "z"
strip = "symbols" # Automatically strip symbols from the binary.
lto = true        # Enable link-time optimization.
debug = false
codegen-units = 4

[dependencies]
anyhow = "1.0.83"
async-trait = "0.1.80"
bollard = "0.16.1"
bollard-stubs = "=1.44.0-rc.2"
bytes = "1.6.0"
figment = { version = "0.10.18", features = ["toml", "yaml", "env", "test"] }
http = "1.1.0"
instant-acme = "0.4.3"
pingora = "0.2.0"
pingora-openssl = "0.2.0"
pingora-http = "0.2.0"
pingora-load-balancing = { version = "0.2.0" }
pingora-pool = "0.2.0"
pingora-proxy = { version = "0.2.0" }
rcgen = { version = "0.13.1", features = ["x509-parser"] }
serde = "1.0.201"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
