[package]
name = "proksi"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
bollard = "0.16.1"
bollard-stubs = "=1.44.0-rc.2"
bytes = "1.6.0"
http = "1.1.0"
instant-acme = "0.4.3"
pingora = "0.1.1"
pingora-boringssl = "0.1.1"
pingora-http = "0.1.1"
pingora-load-balancing = { version = "0.1.1", features = ["boringssl"] }
pingora-pool = "0.1.1"
pingora-proxy = { version = "0.1.1", features = ["boringssl"] }
rcgen = "0.13.1"
serde = "1.0.200"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
