service_name: "proksi"
logging:
  level: "INFO"
  access_logs: true
  error_logs: false
paths:
  tls_certificates: "/etc/proksi/certificates"
  tls_challenges: "/etc/proksi/challenges"
  tls_order: "/etc/proksi/orders"
  tls_account_credentials: "/etc/proksi/account-credentials"
routes:
  - host: "example.com"
    path_prefix: "/api"
    headers:
      add:
        - name: "X-Forwarded-For"
          value: "<value>"
        - name: "X-Api-Version"
          value: "1.0"
      remove:
        - name: "Server"
    upstreams:
      - ip: "10.1.2.24/24"
        port: 3000
        network: "public"
      - ip: "10.1.2.23/24"
        port: 3000
        network: "shared"
